# Site settings
title: (Quang) Minh Pho
email: hi@minhpho.tech
url: https://github.com/jeromelachaud/freelancer-theme
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "[ DevOps engineer , Python developer , Esport enjoyer ]"
skills: "[ DevOps engineer , Python developer , Esport enjoyer ]"
meta_author: Minh Pho

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Minh Pho
  location: Eindhoven, Netherlands
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/quangminhpho
  - title: github
    url: https://github.com/minhpho

# Postal address (add as many lines as necessary)
address:
  - line: hi@minhpho.tech

# Credits content
credits: 'This site is based on Freelancer, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
